resolver: ghc-8.2
compiler: ghc-8.2
system-ghc: true

docker:
  enable: true
  image: tweag/linear-types

packages:
- linear-common
- linear-tests
- linear-watertight
extra-deps:
- ansi-terminal-0.7.1.1
- async-2.1.1.1
- base-compat-0.9.3
- clock-0.7.2
- cmdargs-0.10.18
- code-page-0.1.3
- colour-2.3.3
- doctest-0.13.0
- extra-1.6
- fsnotify-0.2.1.1
- ghc-paths-0.1.0.9
- hinotify-0.3.9
- stm-2.4.4.1
- syb-0.7
- terminal-size-0.3.2.1
- text-1.2.2.2
- unix-compat-0.5
